### PR TITLE
Spelling and dead links

### PR DESCRIPTION
**Pull request by NathanBarta**
Fixed spelling and deadlinks. Did not add content.

- Unclear if BS+MS link is bad or just seasonal.
- http://learningtechlab.pitt.edu/ may be broken.

I've noted various pages needing updates.

### CODE REVIEW

**Review by agrattan0820 — APPROVED** [review]
Hell yeah @NathanBarta, good clean up

**Comment by NathanBarta** [comment]
@agrattan0820 Wiki is getting some love before school starts ❤️ 

Would you mind merging for me? It looks like I'm not authorized.

**Comment by agrattan0820** [comment]
@NathanBarta I changed the permissions for the "pittcsc/officers" group to have Admin permissions (which you're a part of) for this repo, let me know if that allows you to merge or not

**Comment by NathanBarta** [comment]
@agrattan0820 appears so, thanks!

**Pull request merged**
